### ISSUE TITLE
Add `pull_request_target` note to Readme?

### ISSUE THREAD

**Issue by jclem** [paulfantom/periodic-labeler#11]
👋 Hi! Hubber here. I'm curious if we can add a note to the readme of this repository that `pull_request_target` as an event is [now available](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/), and that this new event can be used safely on public repositories. I've outlined how to do this in [this blog post](https://jclem.net/posts/labeling-prs-on-public-github-repositories).

Essentially, it could work with basically the exact same Go code this action uses now, but it could run on actual PR events, rather than on a schedule, which (now) unnecessarily churns through users' Actions minutes.

I also want to say that this repo is an extremely clever hack, and I love it 😄 Just want to make sure people are aware of the new event.

**Comment by paulfantom** [comment]
I am open to PRs :)  Happy to hear about new improvements in GitHub Actions :+1:

**Comment by jclem** [comment]
I'll open a PR today, thanks @paulfantom!
