### ISSUE TITLE
support `**` for zero or more directories 

### ISSUE THREAD

**Issue by ilyam8** [paulfantom/periodic-labeler#7]
Hi @paulfantom 👋 

There is no glob support `**` for zero or more directories in the std lib path pkg

see

https://github.com/golang/go/issues/11862

Following syntax doesnt work

```
# Add '@domain/core' label to any change within the 'core' package
@domain/core:
  - package/core/*
  - package/core/**/*
```

Consider to use https://github.com/gobwas/glob instead

**Comment by ilyam8** [comment]
i am going to do a PR

**Comment by paulfantom** [comment]
Sorry I was not available (no access to internet) for last 30 days. This was a good idea and I merged the PR, thanks for contribution! :+1:

Release is coming soon.

**Comment by ilyam8** [comment]
> no access to internet for last 30 days

Woah dude, how come are you survived 😄
